services:
  - type: web
    name: enterprise-policy-rag
    env: docker
    region: oregon
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    repo: https://github.com/thenileshmishra/enterprise-policy-rag
    autoDeploy: true
    envVars:
      - key: HF_API_KEY
      - key: LLM_API_KEY
      - key: LLM_API_URL
      - key: S3_BUCKET
      - key: S3_ENDPOINT
      - key: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
      - key: FAISS_INDEX_PATH
      - key: FAISS_META_PATH
